export const PUBLIC_API_KEY = "CHAPUBK_TEST-BKiElEuIjshY0RMVHjbEbfHpi95Xh71a";
export const SECRET_API_KEY = "CHASECK_TEST-jLU2TEE6kZo0ytP2Y1iPUV9XRIZBN93O";
export const ENCRIPTION_API_KEY = "CHASECK_0IDBGceUj7ogcEU";
